# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-10.15

variables:
  Configuration: Release
  LogDirectory: $(Build.ArtifactStagingDirectory)/logs

steps:

- script: |
    msbuild Xamarin.Firebase.Messaging.Repro/Xamarin.Firebase.Messaging.Repro.csproj -t:SignAndroidPackage -bl:$(LogDirectory)/msbuild.binlog -restore
  displayName: 'build'

- task: CopyFiles@2
  displayName: copy artifacts
  inputs:
    contents: '**/*-Signed.apk'
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true
  condition: always()

- task: PublishPipelineArtifact@1
  displayName: publish artifacts
  inputs:
    artifactName: artifacts
    targetPath: $(Build.ArtifactStagingDirectory)
  condition: always()
